# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-29 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('SAVINGS', 1), ('CURRENT', 2)], default=1, max_length=30)),
                ('card_no', models.CharField(max_length=16)),
                ('registered_mob_no', models.CharField(max_length=13)),
            ],
        ),
    ]
