# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-29 04:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20170929_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='card_no',
            field=models.CommaSeparatedIntegerField(max_length=16, validators=[django.core.validators.RegexValidator('\\d\\d\\d\\d')]),
        ),
    ]
