# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-29 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20170929_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='account_type',
            field=models.CharField(choices=[(1, 'SAVINGS'), (2, 'CURRENT')], default=1, max_length=30),
        ),
    ]
