# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-29 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20170929_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'SAVINGS'), ('CURRENT', 'CURRENT')], default='SAVINGS', max_length=30),
        ),
    ]
