# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-29 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20170929_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='bank_name',
            field=models.CharField(choices=[('SBI', 1), ('AXIS BANK', 2), ('BANK OF INDIA', 3)], default=1, max_length=50),
        ),
    ]
