# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-29 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20170929_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='account_status',
            field=models.CharField(choices=[('1', 'ACTIVE'), ('2', 'DORMANT')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='bankuser',
            name='current_balance',
            field=models.CharField(default=1000, max_length=20),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='account_type',
            field=models.CharField(choices=[('1', 'SAVINGS'), ('2', 'CURRENT')], default='1', max_length=30),
        ),
    ]
