# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-30 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
        ('bank', '0009_auto_20170929_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'SBI'), ('2', 'AXIS BANK'), ('3', 'BANK OF INDIA')], default=1, max_length=50)),
                ('address', models.TextField(max_length=150)),
                ('ifsc', models.CharField(max_length=20)),
                ('atms', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='atm.ATMMachine')),
            ],
        ),
    ]
