# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-30 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='atms',
        ),
    ]
