# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-30 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmmachine',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='atmmachine',
            name='address',
            field=models.TextField(default='Enter ATM ADDRESS HERE', max_length=500),
        ),
    ]
