# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-29 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_added', models.DateTimeField(auto_now_add=True)),
                ('google_play_account', models.URLField(max_length=30)),
                ('user_name', models.CharField(max_length=50)),
                ('account_password', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('google_play_account',),
            },
        ),
    ]
