# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-29 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0003_bankdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='registered_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.BankUser'),
        ),
    ]
