# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-29 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0004_auto_20170929_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='registered_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bank.BankUser'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='registered_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mobile_app.AppUser'),
        ),
    ]
