# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 03:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_account',
            field=models.CharField(default=1, max_length=11),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_ended_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.datetime(2017, 10, 2, 3, 19, 34, 644977, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='TRANTM<built-in function id>', max_length=150),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_started_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2017, 10, 2, 3, 19, 44, 288838, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('1', 'WITHDRAW'), ('2', 'CREDIT'), ('3', 'TRANSFER')], default='1', max_length=20),
        ),
    ]
