# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0007_auto_20171002_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
