# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0009_transaction_transaction_withdrawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_ended_at',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
